### ISSUE TITLE
Calling LibC functions on macOS via FFI

### ISSUE THREAD

**Issue by kurtkilpela** [GemTalk/FileSystemGs#45]
On Linux, we bind to libc by binding to `libc.so.6`. On macOS, it seems the equivalent in older versions of macOS is called libsystem_c.dylib and is stored in `/usr/lib/system/`. This doesn't appear to exist on Big Sur.

How does macOS expect an FFI to bind to libc and call libc functions? Has this changed w/ Big Sur? Will the implementation have to take this into account?

**Comment by martinmcclure** [comment]
From https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes

New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

...and then the question is how to call dlopen, since that is undoubtedly also in a system-provided library that is not on the filesystem. May need to compile a small C shared library that just dlopen()s a specified library and returns the handle.

**Comment by martinmcclure** [comment]
Although the GemStone FFI should be calling dlopen(), and that should work on a Mac. Perhaps it will just work if the name is correct?

**Comment by kurtkilpela** [comment]
This has been resolved. On macOS, you reference `/usr/lib/libSystem.dylib` and it will automatically be loaded. On older systems, the file exists. On newer, it doesn't exist but the loader handles it correctly.
